### PR TITLE
Fixed multi-dimensional RNG number generation.

### LINKED ISSUE #731: Random doesnt work on  multi dimention array
Hello, 
So there seems to be an issue with random number generators.
If you look at this code here,  It is pretty much the same thing as in the sample:

 ```
public class GAKernels : IDisposable
        {
            private Context Context;
            private CudaAccelerator Accelerator;
            private Random Random;
            private Action<Index1D, RNGView<XorShift128Plus>, ArrayView<long>> KernelMutate;

            public GAKernels()
            {
                  Context = Context.Create(builder => builder.Default().EnableAlgorithms());
                  Accelerator = Context.CreateCudaAccelerator(0);
                  Random = new Random();
                  KernelMutate = Accelerator.LoadAutoGroupedStreamKernel<Index1D, RNGView<XorShift128Plus>, ArrayView<long>>(_Mutate);

                  var input = Accelerator.Allocate1D<long>(100);
                  Mutate(input);

                  var randomValues = input.GetAsArray1D();
                  for (int i = 0, e = randomValues.Length; i < e; ++i)
                      Console.WriteLine($"Random[{i}] = {randomValues[i]}");
        }

        private static void _Mutate(Index1D index, RNGView<XorShift128Plus> rng, ArrayView<long> inputTasks)
        {
            inputTasks[index] = rng.NextLong();
        }
        public void Mutate(MemoryBuffer1D<long,Stride1D.Dense> memoryBufferTasks)
        {
            using var rng = RNG.Create<XorShift128Plus>(Accelerator, Random);
            var rngView = rng.GetView(Accelerator.WarpSize);

            KernelMutate(memoryBufferTasks.IntExtent, rngView, memoryBufferTasks.View);

        }
        public void Dispose()
        {
            Context.Dispose();
        }
    }
```

Here are the results : 
```
Random[0] = 6054234020011121698
Random[1] = 1751383585239879559
Random[2] = 5099157250421567832
Random[3] = 4640065056473717750
Random[4] = 5974222332700202126
Random[5] = 599896564468039205
Random[6] = 5395028641821362495
Random[7] = 8061138114546526523
Random[8] = 8979606570408506752
Random[9] = 1451093514847053956
Random[10] = 8559089394810051872
Random[11] = 4622421309705993140
Random[12] = 8979462517858582170
Random[13] = 558782061588218912
Random[14] = 2470765009546335940
Random[15] = 4663270874655386727
Random[16] = 7823090856736668866
Random[17] = 6812776576108578486
Random[18] = 8085111514713439097
Random[19] = 1423038965051162989
Random[20] = 7125843558899987104
Random[21] = 5746793198581699632
Random[22] = 9152750116339189033
Random[23] = 7876995656440289067
Random[24] = 6351651846224754214
Random[25] = 3580761670390775722
Random[26] = 6221839136158404184
Random[27] = 2064267818006921885
Random[28] = 7061906247041172937
```

As you can see. the number are random so it is working fine.

Now, if we change the arays to be 2d arrays it is not working anymore

The modified code  :

```
public class GAKernels : IDisposable
    {
        private Context Context;
        private CudaAccelerator Accelerator;
        private Random Random;
        private Action<Index2D, RNGView<XorShift128Plus>, ArrayView2D<long, Stride2D.DenseX>> KernelMutate;
        public GAKernels()
        {
            Context = Context.Create(builder => builder.Default().EnableAlgorithms());
            Accelerator = Context.CreateCudaAccelerator(0);

            Random = new Random();


            KernelMutate = Accelerator.LoadAutoGroupedStreamKernel<Index2D, RNGView<XorShift128Plus>, ArrayView2D<long,Stride2D.DenseX>>(_Mutate);
            var input = Accelerator.Allocate2DDenseX<long>(new Index2D(20,20));
            Mutate(input);

            var randomValues = input.GetAsArray2D();
            for (int x = 0; x < randomValues.GetLength(0); ++x)
                for (int y = 0; y < randomValues.GetLength(1); ++y)
                    Console.WriteLine($"Random[{x},{y}] = {randomValues[x,y]}");

            Console.WriteLine();
        }




        private static void _Mutate(Index2D index, RNGView<XorShift128Plus> rng, ArrayView2D<long, Stride2D.DenseX> inputTasks)
        {
            inputTasks[index] = rng.NextLong();
        }
        public void Mutate(MemoryBuffer2D<long,Stride2D.DenseX> memoryBufferTasks)
        {
            using var rng = RNG.Create<XorShift128Plus>(Accelerator, Random);
            var rngView = rng.GetView(Accelerator.WarpSize);

            KernelMutate(memoryBufferTasks.IntExtent, rngView, memoryBufferTasks.View);


        }
        public void Dispose()
        {
            Context.Dispose();
        }
    }
```

The result :

```
Random[0,0] = 6545294719629909752
Random[0,1] = 6545294719629909752
Random[0,2] = 6545294719629909752
Random[0,3] = 6545294719629909752
Random[0,4] = 6545294719629909752
Random[0,5] = 6545294719629909752
Random[0,6] = 6545294719629909752
Random[0,7] = 6545294719629909752
Random[0,8] = 6545294719629909752
Random[0,9] = 6545294719629909752
Random[0,10] = 6545294719629909752
Random[0,11] = 6545294719629909752
Random[0,12] = 6545294719629909752
Random[0,13] = 6545294719629909752
Random[0,14] = 6545294719629909752
Random[0,15] = 6545294719629909752
Random[0,16] = 6545294719629909752
Random[0,17] = 6545294719629909752
Random[0,18] = 6545294719629909752
Random[0,19] = 6545294719629909752
Random[1,0] = 8761621934008506663
Random[1,1] = 8761621934008506663
Random[1,2] = 8761621934008506663
Random[1,3] = 8761621934008506663
Random[1,4] = 8761621934008506663
Random[1,5] = 8761621934008506663
Random[1,6] = 8761621934008506663
Random[1,7] = 8761621934008506663
Random[1,8] = 8761621934008506663
```

As you can see, the numbers are no longer random.

Is there a way to fix it ??

### PR DESCRIPTION
**Pull request by m4rs-mt**
This PR fixes #731 by refining the way the internal RNG states are shared across warps in a thread grid. It also adds some useful helper properties to the `Grid` class.

### CODE REVIEW

File: Src/ILGPU.Algorithms/Random/RNG.cs [hunk 1]
```diff
@@ -158,17 +158,17 @@ protected RNG(Accelerator accelerator)
...
-        private readonly int groupSize;
+        private readonly int maxNumParallelWarps;
 
         /// <summary>
         /// Initializes the RNG view.
         /// </summary>
         /// <param name="providers">The random providers.</param>
-        /// <param name="numParallelGroups">The maximum number of parallel groups.</param>
-        internal RNGView(ArrayView<TRandomProvider> providers, int numParallelGroups)
+        /// <param name="numParallelWarps">The maximum number of parallel groups.</param>
```
Comment (MoFtZ) [inline Src/ILGPU.Algorithms/Random/RNG.cs:167]: MINOR: Comment not updated.
```suggestion
        /// <param name="numParallelWarps">The maximum number of parallel warps.</param>
```

**Review by MoFtZ — CHANGES_REQUESTED** [review]
ISSUE: Need to update the copyright headers.

`dotnet run --configuration=Release -p:TreatWarningsAsErrors=true --project Tools/CopyrightUpdateTool`

**Review by MoFtZ — APPROVED** [review]
